#message( STATUS "Find png" )

find_path(SDL_IMAGE_INCLUDE_DIR SDL_image.h
  PATHS ${CMAKE_INSTALL_PREFIX}/include
  NO_DEFAULT_PATH
  PATH_SUFFIXES SDL_Image 
)

find_library(SDL_IMAGE_LIBRARY_RELEASE
  PATHS ${CMAKE_INSTALL_PREFIX}/lib
  NO_DEFAULT_PATH
  NAMES sdl_image 
)

find_library(SDL_IMAGE_LIBRARY_DEBUG
  PATHS ${CMAKE_INSTALL_PREFIX}/lib
  NO_DEFAULT_PATH
  NAMES sdl_imaged 
)

#MESSAGE( STATUS "FindSDL_IMAGE: SDL_IMAGE_LIBRARY_DEBUG: ${SDL_IMAGE_LIBRARY_DEBUG}" )
#MESSAGE( STATUS "FindSDL_IMAGE: SDL_IMAGE_LIBRARY_RELEASE: ${SDL_IMAGE_LIBRARY_RELEASE}" )





include(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/SelectLibraryConfigurations.cmake)
select_library_configurations(SDL_IMAGE)


FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL_IMAGE
                                  REQUIRED_VARS SDL_IMAGE_LIBRARY SDL_IMAGE_INCLUDE_DIR)

