#message( STATUS "Findng Jsoncpp" )

find_path(JSONCPP_INCLUDE_DIR json.h
  PATHS ${CMAKE_INSTALL_PREFIX}/include
  NO_DEFAULT_PATH
  PATH_SUFFIXES json
)
#find_path(TEST_INCLUDE_DIR test.h
#  PATHS ${CMAKE_INSTALL_PREFIX}/include
#  ${CMAKE_INSTALL_PREFIX}
#  PATH_SUFFIXES test 
#)
#
#MESSAGE( STATUS "Zlib: CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}" )
#MESSAGE( STATUS "Zlib: TEST_INCLUDE_DIR: ${TEST_INCLUDE_DIR}" )
#
#
#MESSAGE( STATUS "FindZlib: ZLIB_INCLUDE_DIR: ${ZLIB_INCLUDE_DIR}" )



